pub mod bitboards;
pub mod board;
pub mod square;
mod tests;
pub mod magic;
pub mod castling;
pub mod movement;
pub mod piece;
pub mod perft;
pub mod alphabeta;
pub mod evaluation;
pub mod zobrist;
pub mod transposition;
pub mod mcts;
