[package]
name = "rusty_brain"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.14.0", features = ["train", "wgpu", "vision", "ndarray"] }
burn-cuda = "0.14.0"
rand = "0.8.5"
rough_guard = { path = "../rough_guard" }
nnue = { path = "../nnue" }
