[package]
name = "hook_lens"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.14.0", features = ["train", "wgpu", "vision"] }
serde = "*"
image = "*"
opencv="*"
rusty_brain = {path = "../rusty_brain"}