[package]
name = "rough_guard"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.14.0", features = ["train", "wgpu", "vision"] }
burn-cuda = "0.14.0"
burn-dataset = "*"
serde = "*"
once_cell = "1.21.1"